project:
  type: website

website:
  title: "Harnessing Renewable Power: Australia's Journey"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/akshatamhaski
format:
  html:
    theme: litera
    css: styles.css



